#!/usr/bin/env bash

# Theme switching orchestrator for Sway dotfiles
# Usage: ~/.config/sway/themes/theme.sh <theme-name>
# Example: ~/.config/sway/themes/theme.sh dracula

set -euo pipefail

THEME_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/sway/themes"
ACTIVE_CONF="$THEME_DIR/active.conf"
GENERATED_DIR="$THEME_DIR/generated"

# Ensure generated directory exists
mkdir -p "$GENERATED_DIR"

# Validate arguments
if [[ $# -lt 1 ]]; then
    echo "Usage: $(basename "$0") <theme-name>"
    echo ""
    echo "Available themes:"
    ls -1 "$THEME_DIR"/*.conf 2>/dev/null | \
        xargs -I {} basename {} .conf | \
        grep -v "^active$" | \
        sort
    exit 1
fi

REQUESTED_THEME="$1"
THEME_FILE="$THEME_DIR/${REQUESTED_THEME}.conf"

# Validate theme exists
if [[ ! -f "$THEME_FILE" ]]; then
    echo "Error: Theme not found: $THEME_FILE" >&2
    exit 1
fi

echo "Switching to theme: $REQUESTED_THEME"

# ============================================
# Generate active.conf from theme definition
# ============================================

cat > "$ACTIVE_CONF" << 'EOF'
# Active theme configuration
# This file is generated by theme.sh - do NOT edit manually
# Run: ~/.config/sway/themes/theme.sh <theme-name>

EOF

echo "# Current active theme: $REQUESTED_THEME" >> "$ACTIVE_CONF"
echo "" >> "$ACTIVE_CONF"

# Extract and append theme colors
sed -n '/^set \$\(background-color\|text-color\|accent-color\|selection-color\|color[0-9]*\) /p' \
    "$THEME_FILE" >> "$ACTIVE_CONF"

# ============================================
# Generate application-specific theme files
# ============================================

# Extract colors for use in generation
eval "$(sed -n '/^set \$\(background-color\|text-color\|accent-color\|color[0-9]*\) /p' "$THEME_FILE" | \
    sed "s/set //g" | sed "s/ //g")"

# Generate Waybar colors.css
cat > "$GENERATED_DIR/waybar-colors.css" << EOF
/* Generated waybar colors from theme: $REQUESTED_THEME */

@define-color accent $accent-color;
@define-color background $background-color;
@define-color foreground $text-color;
@define-color selection $selection-color;

window {
    background-color: $background-color;
    color: $text-color;
}

button:hover {
    background-color: $selection-color;
}

button.focused {
    background-color: $accent-color;
    color: $background-color;
}
EOF

echo "✓ Generated Waybar colors"

# Generate Mako colors configuration
cat > "$GENERATED_DIR/mako-colors" << EOF
# Generated mako colors from theme: $REQUESTED_THEME
border-color=$accent-color
background-color=$background-color
text-color=$text-color
EOF

echo "✓ Generated Mako colors"

# Generate Wofi colors CSS
cat > "$GENERATED_DIR/wofi-colors.css" << EOF
/* Generated wofi colors from theme: $REQUESTED_THEME */

* {
    background-color: $background-color;
    color: $text-color;
    border-color: $accent-color;
}

#entry:selected {
    background-color: $accent-color;
    color: $background-color;
}
EOF

echo "✓ Generated Wofi colors"

# Generate Foot theme
cat > "$GENERATED_DIR/foot-colors.ini" << EOF
# Generated foot colors from theme: $REQUESTED_THEME

[colors]
alpha=0.95
foreground=$text-color
background=$background-color

regular0=$color0
regular1=$color8
regular2=$color11
regular3=$color10
regular4=$color12
regular5=$color14
regular6=$color13
regular7=$color5

bright0=$color1
bright1=$color8
bright2=$color11
bright3=$color10
bright4=$color12
bright5=$color14
bright6=$color13
bright7=$color6
EOF

echo "✓ Generated Foot colors"

# ============================================
# Reload/Restart Applications
# ============================================

echo ""
echo "Updating running applications..."

# Reload Sway if connected
if command -v swaymsg >/dev/null 2>&1 && pgrep -q sway; then
    swaymsg reload
    echo "✓ Reloaded Sway"
fi

# Restart Waybar if running
if pgrep -q waybar; then
    pkill waybar
    sleep 0.5
    if [[ -x /usr/bin/waybar ]] || command -v waybar >/dev/null 2>&1; then
        waybar &
        echo "✓ Restarted Waybar"
    fi
fi

# Restart Mako if running
if pgrep -q mako; then
    pkill mako
    sleep 0.5
    if [[ -x /usr/bin/mako ]] || command -v mako >/dev/null 2>&1; then
        mako &
        echo "✓ Restarted Mako"
    fi
fi

echo ""
echo "=========================================="
echo "Theme switched to: $REQUESTED_THEME"
echo "=========================================="
echo ""
echo "Generated files:"
echo "  • $GENERATED_DIR/waybar-colors.css"
echo "  • $GENERATED_DIR/mako-colors"
echo "  • $GENERATED_DIR/wofi-colors.css"
echo "  • $GENERATED_DIR/foot-colors.ini"
echo ""
echo "Active theme: $ACTIVE_CONF"
