#!/usr/bin/env bash

set -euo pipefail

DOTFILES="$HOME/dotfiles"
CONFIG="$DOTFILES/.config"

REPO_BASE="https://raw.githubusercontent.com/manjaro-sway/desktop-settings/sway/community/sway"

echo "======================================"
echo "   Creating Sway dotfiles repository"
echo "======================================"
echo

mkdir -p "$DOTFILES"

# --------------------------------------------------
# Create directory structure
# --------------------------------------------------

mkdir -p \
    "$CONFIG/sway/config.d" \
    "$CONFIG/sway/definitions.d" \
    "$CONFIG/sway/inputs" \
    "$CONFIG/sway/modes" \
    "$CONFIG/sway/scripts" \
    "$CONFIG/sway/themes" \
    "$CONFIG/waybar" \
    "$CONFIG/foot/themes" \
    "$CONFIG/mako" \
    "$CONFIG/wofi" \
    "$CONFIG/swaylock" \
    "$CONFIG/swappy" \
    "$CONFIG/gtk-3.0" \
    "$CONFIG/gtk-4.0" \
    "$CONFIG/systemd/user" \
    "$CONFIG/zsh/config.d" \
    "$CONFIG/nvim"

mkdir -p \
    "$DOTFILES/packages"

echo "Directory structure created."

# --------------------------------------------------
# Download helper
# --------------------------------------------------

download() {
    local remote="$1"
    local local_file="$2"

    mkdir -p "$(dirname "$local_file")"

    echo "Downloading:"
    echo "  $remote"
    echo "  -> $local_file"

    curl -fL \
        "$REPO_BASE/$remote" \
        -o "$local_file"
}

# --------------------------------------------------
# Manjaro Sway user configuration
# --------------------------------------------------

echo
echo "=== Sway configuration ==="

download \
    "etc/skel/.config/sway/config" \
    "$CONFIG/sway/config"

download \
    "etc/skel/.config/sway/definitions.d/README.md" \
    "$CONFIG/sway/definitions.d/README.md"

download \
    "etc/skel/.config/sway/definitions.d/theme.conf" \
    "$CONFIG/sway/definitions.d/theme.conf"

download \
    "etc/skel/.config/sway/config.d/README.md" \
    "$CONFIG/sway/config.d/README.md"

# --------------------------------------------------
# Sway modes
# --------------------------------------------------

echo
echo "=== Sway modes ==="

for file in \
    default \
    recording \
    resize \
    scratchpad \
    screenshot \
    shutdown
do
    download \
        "etc/sway/modes/$file" \
        "$CONFIG/sway/modes/$file.conf"
done

# --------------------------------------------------
# Sway input configuration
# --------------------------------------------------

echo
echo "=== Sway inputs ==="

download \
    "etc/sway/inputs/default-keyboard" \
    "$CONFIG/sway/inputs/keyboard.conf"

download \
    "etc/sway/inputs/default-touchpad" \
    "$CONFIG/sway/inputs/touchpad.conf"

# --------------------------------------------------
# Manjaro Sway scripts
# --------------------------------------------------

echo
echo "=== Sway scripts ==="

SCRIPTS=(
    brightness.sh
    checkupdates.sh
    dnd.sh
    enable-cursor-theme.sh
    enable-gtk-theme.sh
    first-empty-workspace.py
    fontconfig.sh
    foot.sh
    generate-bg.sh
    generate-displays-config.sh
    generate-waybar-style.sh
    geoip.sh
    gh-notifications.sh
    help.sh
    keyboard-backlight-switch.sh
    keyboard.sh
    lock.sh
    mako.sh
    once.sh
    recorder.sh
    scale.sh
    scratchpad.sh
    sunset.sh
    theme-toggle.sh
    update-vscode-settings.sh
    update-zed-settings.sh
    waybar.sh
    weather.py
    wluma.sh
    wob.sh
    zeit.sh
)

for file in "${SCRIPTS[@]}"; do
    download \
        "usr/share/sway/scripts/$file" \
        "$CONFIG/sway/scripts/$file"
done

# --------------------------------------------------
# Matcha Green theme
# --------------------------------------------------

echo
echo "=== Matcha Green theme ==="

mkdir -p "$CONFIG/sway/themes/matcha-green"

download \
    "usr/share/sway/themes/matcha-green/theme.conf" \
    "$CONFIG/sway/themes/matcha-green/theme.conf"

download \
    "usr/share/sway/themes/matcha-green/foot-theme.ini" \
    "$CONFIG/sway/themes/matcha-green/foot-theme.ini"

# --------------------------------------------------
# Waybar
# --------------------------------------------------

echo
echo "=== Waybar ==="

download \
    "etc/skel/.config/waybar/config.jsonc.example" \
    "$CONFIG/waybar/config.jsonc"

download \
    "etc/skel/.config/waybar/style.css.example" \
    "$CONFIG/waybar/style.css"

# --------------------------------------------------
# Foot
# --------------------------------------------------

echo
echo "=== Foot ==="

download \
    "etc/skel/.config/foot/foot.ini.example" \
    "$CONFIG/foot/foot.ini"

# --------------------------------------------------
# Mako
# --------------------------------------------------

echo
echo "=== Mako ==="

# Mako is generated by the Manjaro scripts/templates,
# so we create the directory now and let Copilot adapt
# the actual configuration later.

touch "$CONFIG/mako/config"

# --------------------------------------------------
# Swappy
# --------------------------------------------------

echo
echo "=== Swappy ==="

download \
    "etc/skel/.config/swappy/config" \
    "$CONFIG/swappy/config"

# --------------------------------------------------
# Zsh
# --------------------------------------------------

echo
echo "=== Zsh ==="

download \
    "etc/skel/.config/zsh/.zshrc" \
    "$CONFIG/zsh/.zshrc"

# --------------------------------------------------
# Gitignore
# --------------------------------------------------

cat > "$DOTFILES/.gitignore" <<'EOF'
# Runtime / generated files
.config/**/*.cache
.config/**/*.log

# Neovim
.config/nvim/.luarc.json

# OS metadata
.DS_Store
Thumbs.db

# Secrets
.env
.env.*
*.secret

# Temporary files
*.tmp
*.swp
*.swo
EOF

# --------------------------------------------------
# README
# --------------------------------------------------

cat > "$DOTFILES/README.md" <<'EOF'
# Portable Sway Dotfiles

Personal Linux desktop configuration based initially on the Manjaro
Sway desktop-settings project.

The repository is intentionally user-local and portable. It keeps the
configuration in the user profile and avoids system-wide desktop paths.

## Structure

- `.config/sway` - Sway configuration, scripts, modes and themes
- `.config/waybar` - Waybar
- `.config/foot` - Foot terminal
- `.config/mako` - notifications
- `.config/wofi` - application launcher
- `.config/systemd/user` - user services
- `.config/zsh` - Zsh configuration
- `packages/` - distribution-specific dependencies

## Deployment

Use the deployment script to copy the repository configuration
into the real user's ~/.config directory.

No symlinks are used.
EOF

echo
echo "======================================"
echo " Initial import complete!"
echo "======================================"
echo
echo "Repository:"
echo "  $DOTFILES"
echo
echo "Review the files before deploying."